name: hidden_drawer
description: Hidden Drawer start like a fork of https://github.com/RafaelBarbosatec/hidden_drawer_menu and https://www.youtube.com/watch?v=6CEjnCVdgRM with custom changes to work in my projects
version: 0.0.1
author: Bwolf<bwolf@flutterando.com>
homepage: https://github.com/bwolfs2/hidden_drawer

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

